name: Discord Notification

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"New Issue: ${{ github.event.issue.title }}\n${{ github.event.issue.html_url }}\"}" \
          ${{ secrets.DISCORDBOT }}
